# Generated by Django 3.1.3 on 2021-07-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
