# Generated by Django 3.1.3 on 2021-07-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20210719_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
